### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by touzi** [SuLingGG/Action-OpenWrt-Plus#4]
fork 后拷贝 template/lean/rpi3-lean-openwrt.config 到 config/lean 目录下, 自动触发编译不成功. 
![image](https://user-images.githubusercontent.com/3685924/92995611-8ca74400-f537-11ea-92f6-7c5e8b1eba33.png)
![image](https://user-images.githubusercontent.com/3685924/92995619-a052aa80-f537-11ea-8bde-e054be8a65c8.png)
![image](https://user-images.githubusercontent.com/3685924/92995635-c24c2d00-f537-11ea-99de-f6e7ad23bb10.png)
大佬看看是什么问题.

**Comment by SuLingGG** [comment]
如果没有别的需求还是用我的现成固件吧...
这个项目在以后没准会归档不再维护(同时维护两个项目太费精力了)。
